<?php 
if ($formType == 'new' ){
	$disabledselect = "";
	$readonly		= "";
}elseif ($formType == 'edit' ){
	$disabledselect = "pointer-events: none;";
	$readonly		= "readonly";
}elseif ($formType == 'view' ){
	$disabledselect = "pointer-events: none;";
	$readonly		= "readonly";
}
$save = $save_link;
?>

<?php echo form_open("procurement$save");?>
<div class="ui-middle-screen">
	<div class="content-workorder">
		<div class="div-p"></div>
		<div class="ui-main-form">
			<div class="ui-main-form-header">
				<table align="center" height="40px" border="0">
					<tr>
						<td><span style="margin-left:10px;">New Release NOTE <?=$formType?></span></td>
					</tr>
				</table>
			</div>
			<div class="n-req">Release Note number will be automatically generated by the system.</div>
			<div class="ui-main-form-5">
				<div class="middle_d">
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Information</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<div style="color: red; padding-left: 20px;"><?=validation_errors();?></div>
								<p style="color: red; padding-left: 20px; display: none;" id="error_message-status">*Please select status</p>
								<p style="color: red; padding-left: 20px; display: none;" id="error_message-area">*Please select area</p>
								<div class="ui-main-form-1">
									<div class="middle_d">
										<table width="100%" class="ui-content-form-reg" style="">
											<tr >
												<td class="ui-desk-style-table">
													<table class="ui-content-form" width="100%" border="0">
														<tr>
															<td style="padding:10px;" valign="top" class="ui-w">*Status  :</td>
														<td style="padding:10px;" valign="top">
															<?php 
																$list_option = array(""=>"Select", "0"=>"Submitted");
																$Status_list = array(
																				"name" => "rn_status",
																				"class" => "dropdown n_wi-date2",
																				"style" => "display:inline-block; width:100px; height:30px; $disabledselect",
																				"set_value" => "rn_status"
																);
															?>   
																<?php if ($formType == 'new' ||$formType == 'edit'){ ?>
															<?php echo form_dropdown($Status_list, $list_option); ?>
															<?php } else { ?>
															<?=($rndet[0]->rn_status==0) ? 'Send' :''?>
															<?php } ?>
															</td>
														</tr>
														<!-- <tr>
															<td style="padding:10px;" valign="top">Release Note Type :   </td>
															<td style="padding:10px;" valign="top"> MRIN </td>
														</tr> -->
														<tr>
															<td style="padding-left:10px;" valign="top" colspan="2"><u>FROM</u>  </td>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Contact Person :  </td>
															<?php if ($formType == 'new' ||$formType == 'edit' ){ ?>
															<td style="padding:10px;" valign="top"> <?=$this->session->userdata("fullname")?> </td>
														    <?php }else{ ?>
															<td style="padding:10px;" valign="top"> <?=$rndet[0]->relname?> </td>
															<?php } ?>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Area  :  </td>
															<td style="padding:10px;" valign="top"> <?=$this->session->userdata("hosp_code")?> </td>
														</tr>														
														<tr>
															<td style="padding-left:10px;" valign="top" colspan="2"><u>DELIVER TO</u>  </td>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Contact Person :  </td>
															<?php if ($formType == 'new'||$formType == 'edit'){ ?>
															<td style="padding:10px;" valign="top"> <input style="border:0px; width: 90%;" type="text" name="to_contact_person" id="to_contact_person" value="<?=set_value('to_contact_person'); ?>" readonly /> </td>
															<?php }else { ?>
															<td style="padding:10px;" valign="top"> <?=$rndet[0]->repname;?> </td>
														    <?php } ?>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">*Area  :  </td>
																<?php if ($formType == 'new' || $formType == 'edit'){ ?>
															<td style="padding:10px;" valign="top">
															
																<?php 
																$area_option = array(""=>"Please");
																if( !empty($arealist) ){
																	foreach ($arealist as $row) {
																		$area_option[$row['v_HospitalCode']] = $row["v_HospitalName"];
																	}
																}
																$Area_list = array(
																				"name" => "area",
																				"class" => "dropdown n_wi-date2",
																				"style" => "display:inline-block; width:100px; height:30px; $disabledselect",
																				"set_value" => "area",
																				// "onchange" => "get_dataItem(this)"										
																);
																// if ($this->input->get('pro') == 'new' ){
																if ($formType == 'new' ){
																	$Area_list["onchange"] = "get_dataItem(this)";
																}/*elseif ($formType == 'edit' )if ($this->input->get('pro') == 'edit' ){
																	$Area_list["onload"] = "get_dataItem(this,'edit-')";
																}*/

																echo form_dropdown($Area_list, $area_option); ?> 
															</td>
															<?php }else{ ?>
															<td style="padding:10px;" valign="top"><?=$rndet[0]->hosp;?></td>
															<?php } ?>
														</tr>
														<!--<tr>
															<td style="padding:10px;" valign="top">Date From :    </td>
															<td style="padding:10px;" valign="top"> 
																<input type="text" name="datefrom" value="<?=set_value('datefrom');?>" id="date1" class="form-control-button2 n_wi-date2" style="<?=$disabledselect;?>" autocomplete="off" <?=$readonly;?> onchange="get_dataItem(this)" >
															</td>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Date To :    </td>
															<td style="padding:10px;" valign="top"> 
																<input type="text" name="dateto" value="<?=set_value('dateto');?>" id="date2" class="form-control-button2 n_wi-date2" style="<?=$disabledselect;?>" autocomplete="off" <?=$readonly;?> onchange="get_dataItem(this)" >
															</td>
														</tr>-->
													</table>
												</td>
											</tr>
										</table>
									</div>
								</div>
								<div class="ui-main-form-2">
									<div class="middle_d">
										<table class="ui-content-form-reg">
											<tr >
												<td class="ui-desk-style-table">
													<table class="ui-content-form" style="color:black;" width="100%" border="0">
														<tr>
															<td style="padding-left:10px;" valign="top" colspan="2"><u>SHIPPING INFO</u>  </td>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top" class="ui-w">Shipment Type  :  </td>
														    <?php if ($formType == 'new'||$formType == 'edit'){ ?>
															<td style="padding-left:10px;" valign="top"> 
																<?php 
																$Shipment_option = array(
																		  '0' => 'Courier',
																		  '1' => 'By hand',															
																);
																$Shipment_list = array(
																		"name" => "shipment_type",
																		"class" => "dropdown n_wi-date2",
																		"style" => "display:inline-block; width:100px; height:30px; $disabledselect",
																		"set_value" => "shipment_type"
																);
																echo form_dropdown($Shipment_list , $Shipment_option); ?> 
															</td>
															<?php }else{?>
															<td style="padding-left:10px;" valign="top"> <?=$rndet[0]->sh_type;?></td>
															<?php } ?>
															
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Courier Company  :  </td>
															<?php if ($formType == 'new' || $formType == 'edit'){ ?>
															<td style="padding-left:10px;" valign="top"> 
																<?php 
																$Courier_option = array(
																		  '0' => 'Other',
																		  '1' => 'ABX',
																		  '2' => 'CityLink',
																		  '3' => 'DHL',															
																	   );
																$Courier_list = array(
																	"name" => "courier",
																	"class" => "dropdown n_wi-date2",
																	"style" => "display:inline-block; width:100px; height:30px; $disabledselect",
																	"set_value" => "courier"
																);
																echo form_dropdown($Courier_list, $Courier_option); ?>
															</td>
															<?php }else{ ?>
																<td style="padding-left:10px;" valign="top"><?=$rndet[0]->courier;?></td>
															<?php } ?>
															
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Consignment Note :    </td>
															<td style="padding:10px;" valign="top"> 
															<?php if ($formType == 'new' || $formType == 'edit' ){ ?>
																<input type="text" name="consignment_note" value="<?=set_value('consignment_note'); ?>" class="form-control-button2 n_wi-date2" autocomplete="off" <?=$readonly;?> >
	                                                           <?php } else { ?>
                                                                <?=$rndet[0]->consignment_note;?>
															   <?php } ?>	
															</td>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Consignment Date :    </td>
															<td style="padding:10px;" valign="top"> 
																<?php if ($formType == 'new'||$formType == 'edit' ){ ?>
																<input type="text" name="consignment_date" value="<?=set_value('consignment_date');?>" id="date0" class="form-control-button2 n_wi-date2" style="<?=$disabledselect;?>" autocomplete="off" <?=$readonly;?> >
															  <?php } else{ ?>
                                                               <?=date('d/m/Y',strtotime($rndet[0]->consignment_date));?>
															   <?php } ?>	
															</td>
														</tr>
														<tr>
															<td style="padding-left:10px;" class="ui-w" valign="top">Accessories  :   </td>
															<td style="padding-left:10px;" >
																<?php if ($formType == 'new' || $formType == 'edit' ){ ?>
																<textarea class="Input n_com2" name="accessories" <?=$readonly;?> ><?=set_value('accessories')?></textarea>
															   <?php } else { ?>
                                                              <textarea class="Input n_com2" name="accessories"><?=$rndet[0]->accessories;?></textarea>
															   <?php } ?>
															</td>
														</tr>
													</table>
												</td>
											</tr>						
										</table>
									</div>
								</div>
							</td>
						</tr>						
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Item Specification</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<?php //if ($this->input->get('pro') == 'new' ){?>
								<?php if ($formType == 'new' ){?>
								<!-- <table class="ui-content-form" style="color:black;" width="100%" border="0">
									<tr>
										<td style="padding:10px; width:15%;" valign="top">Item(s)   :   </td>
										<td style="padding:10px;"></td>
									</tr>
								</table> -->

									<span style="padding: 10px; color: black;">Item(s) :</span><br>
									<div class="ui-desk-style-table">
										<div class="ui-desk-style-table">
											<table id="item-tables" data-table="items" class="ui-content-form" style="color:black; margin: 1%;" width="98%" border="0">
												<thead>
													<tr>
														<th>No</th>
														<th>Item Code</th>
														<th>Item Name</th>
														<th>MRIN Ref No.</th>
														<th>Qty Req</th>
														<th>Qty In-Store</th>
														<th>Qty Release</th>
													</tr>
												</thead>
												<tbody id="item-table-value"><?=$data_item_specification;?></tbody>
											</table>
										</div>
									</div>

								<?php //}elseif ($this->input->get('pro') == 'edit' ){?>
								<?php }elseif ($formType == 'edit' ){?>
								<style>table.wnctable th {background:#66b2b2 ;}</style>
								<table class="wnctable" border="1" style="text-align:center; margin:5px auto;" align="center">
									<thead>
										<tr>
											<th>No</th>
											<th>Item Code</th>
											<th>Item Name</th>
											<th>MRIN Ref No.</th>
											<th>Qty Req</th>
											<th>Qty In-Store</th>
											<th>Qty Release</th>
										</tr>
									</thead>
									<tbody>
										<?=$data_item_specification;?>
									</tbody>
								</table>
								<?php }elseif($formType == 'view' ){?>
									<style>table.wnctable th {background:#66b2b2 ;}</style>
								<table class="wnctable" border="1" style="text-align:center; margin:5px auto;" align="center">
									<thead>
										<tr>
											<th>No</th>
											<th>Item Code</th>
											<th>Item Name</th>
											<th>MRIN Ref No.</th>
											<th>Qty Release</th>
										</tr>
									</thead>
									<tbody>
										<?=$data_item_specification;?>
									</tbody>
								</table>
								<?php } ?>
							</td>
						</tr>						
					</table>
				</div>
			</div>
			<table align="center" height="40px" border="0" style="width:100%;" class="ui-main-form-footer">
				<tr>
					<td align="center">
					<?php if($formType <> 'view' ){?>
						<input type="submit" class="btn-button btn-primary-button" name="mysubmit" value="Save" style="width:150px;"/>
						<input type="button" class="btn-button btn-primary-button" name="Cancel" value="Cancel" onclick="window.history.back()" style="width:150px;"/>
					<?php } ?>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>

<script type="text/javascript">
	function get_dataItem(d){
	
		// var code = $(d).val();
		var area 	= $("select[name=area]").val();
			//alert(area);
		//var datefrom= $("input[name=datefrom]").val();
		//var dateto	= $("input[name=dateto]").val();

		$.post("<?=site_url()?>/procurement/releaseNote_get_itemspecification", { site:area } ,function(data){
		//$.post("<?=site_url()?>/procurement/releaseNote_get_itemspecification", { site:area,datefrom:datefrom,dateto:dateto } ,function(data){
			var obj = JSON.parse(data);
				//alert(area);
			$("tbody#item-table-value").html(obj.table);
			$("#to_contact_person").val(obj.v_head_of_lls);
		});
	
	}

	// $("input[name=mysubmit]").closest("form").submit( function(){
	// 	if( $("select[name=rn_status]").val()=="" || $("select[name=area]").val()=="" ){
	// 		if( $("select[name=rn_status]").val()=="" ){
	// 			$("select[name=rn_status]").css("border-color", "red");
	// 			$("#error_message-status").show();
	// 		}else{
	// 			$("select[name=rn_status]").css("border-color", "");
	// 			$("#error_message-status").hide();
	// 		}
	// 		if( $("select[name=area]").val()=="" ){
	// 			$("select[name=area]").css("border-color", "red");
	// 			$("#error_message-area").show();
	// 		}else{
	// 			$("select[name=area]").css("border-color", "");
	// 			$("#error_message-area").hide();
	// 		}
	// 		return false;
	// 	}
	// });
</script>
<style>
	.icon{
		font-size:14px;
		margin-right:5px;
		margin-left:5px;
		color:red;
		display:iniline-block;
	}
	.icon2{
		font-size:14px;
		margin-left:5px;
		color:green;
	}



	@media screen and (max-width: 960px) {
		/* Force table to not be like tables anymore */
		/*#item-tables table, 
		#item-tables thead, 
		#item-tables tbody, 
		#item-tables th, 
		#item-tables td, 
		#item-tables tr { 
			display: block; 
		}*/

		/* Hide table headers (but not display: none;, for accessibility) */
		/*#item-tables thead tr th{ 
			position: absolute;
			top: -9999px;
			left: -9999px;
		}*/

		/*#item-tables td { 
			border: none;
			position: relative;
			padding-left: 50%; 
			white-space: normal;
			text-align:left;
		}*/

		/*#item-tables td:before() { 
			border:1px solid yellow;
		}*/

		/*
		Label the data
		*/
		/*#item-tables td:before(2){ content: "aaa"; }*/



		#item-tables{width:98%;}
		#item-tables,#item-tables thead,#item-tables tbody,#item-tables th,#item-tables td,#item-tables tr { 
				display: block; 
				color:black;
		}

		/* Hide table headers (but not display: none;, for accessibility) */
		#item-tables tr th{ 
			position: absolute;
			top: -9999px;
			left: -9999px;
		}

		#item-tables tr { border: 1px solid #ccc; }

		#item-tables td { 
			/* Behave  like a "row" */
			border: none;
			border-bottom: 1px solid #eee; 
			position: relative;
			padding-left: 50%;
			min-height: 26px;
		}

		#item-tables td:before { 
			/* Now like a table header */
			position: absolute;
			/* Top/left values mimic padding */
			top: 3px;
			left: 6px;
			width: 45%; 
			padding-right: 10px; 
			white-space: nowrap;
		}

		/*
		Label the data
		*/
		#item-tables[data-table="items"] td:nth-of-type(1):before { content: "No :"; }
		#item-tables[data-table="items"] td:nth-of-type(2):before { content: "Transaction Date :"; }
		#item-tables[data-table="items"] td:nth-of-type(3):before { content: "Documentation :"; }
		#item-tables[data-table="items"] td:nth-of-type(4):before { content: "User :"; }
		#item-tables[data-table="items"] td:nth-of-type(5):before { content: "In :"; }
		#item-tables[data-table="items"] td:nth-of-type(6):before { content: "Out :"; }
		#item-tables[data-table="items"] td:nth-of-type(7):before { content: "Balance :"; }
		#item-tables[data-table="items"] td:nth-of-type(8):before { content: "Remark :"; }
	}

	input.readonly{
		border:0px;
	}
</style>
</body>
<?php include 'content_jv_popup.php';?>
<?php echo form_close(); ?>
</html>
